CREATE TABLE IF NOT EXISTS person (
id UUID DEFAULT gen_random_uuid(),
name CHARACTER VARYING(10) NOT NULL,
surname CHARACTER VARYING(20) NOT NULL,
email CHARACTER VARYING(45) NOT NULL,
citizenship CHARACTER VARYING(25) NOT NULL,
age SMALLINT NOT NULL,

UNIQUE(email),
PRIMARY KEY(id)
);
