Insert Into person(name, surname, email, citizenship, age) VALUES('Anna', 'Petrova', 'anna@gmail.com', 'Russia', 23);
Insert Into person(name, surname, email, citizenship, age) VALUES('David', 'Lee', 'david@yahoo.com', 'South Korea', 31);
Insert Into person(name, surname, email, citizenship, age) VALUES('Maria', 'Garcia', 'maria@hotmail.com', 'Spain', 27);
Insert Into person(name, surname, email, citizenship, age) VALUES('John', 'Smith', 'john@gmail.com', 'USA', 29);
Insert Into person(name, surname, email, citizenship, age) VALUES('Emma', 'Müller', 'emma@yahoo.com', 'Germany', 25);
Insert Into person(name, surname, email, citizenship, age) VALUES('Ali', 'Ahmed', 'ali@hotmail.com', 'Egypt', 33);
Insert Into person(name, surname, email, citizenship, age) VALUES('Sophie', 'Martin', 'sophie@gmail.com', 'France', 24);
Insert Into person(name, surname, email, citizenship, age) VALUES('Liu', 'Wang', 'liu@yahoo.com', 'China', 28);
Insert Into person(name, surname, email, citizenship, age) VALUES('Carlos', 'Santos', 'carlos@hotmail.com', 'Brazil', 26);
Insert Into person(name, surname, email, citizenship, age) VALUES('Sarah', 'Jones', 'sarah@gmail.com', 'UK', 30);
Insert Into person(name, surname, email, citizenship, age) VALUES('Mohamed', 'Abdullah', 'mohamed@yahoo.com', 'Saudi Arabia', 32);
Insert Into person(name, surname, email, citizenship, age) VALUES('Laura', 'Rossi', 'laura@hotmail.com', 'Italy', 22);
Insert Into person(name, surname, email, citizenship, age) VALUES('James', 'Wilson', 'james@gmail.com', 'Canada', 34);
Insert Into person(name, surname, email, citizenship, age) VALUES('Eva', 'Novak', 'eva@yahoo.com', 'Czech Republic', 21);
Insert Into person(name, surname, email, citizenship, age) VALUES('Ahmed', 'Khan', 'ahmed@hotmail.com', 'Pakistan', 35);
Insert Into person(name, surname, email, citizenship, age) VALUES('Lisa', 'Andersen', 'lisa@gmail.com', 'Denmark', 23);
Insert Into person(name, surname, email, citizenship, age) VALUES('Kim', 'Park', 'kim@yahoo.com', 'North Korea', 31);
Insert Into person(name, surname, email, citizenship, age) VALUES('Diego', 'Gomez', 'diego@hotmail.com', 'Mexico', 27);
Insert Into person(name, surname, email, citizenship, age) VALUES('Mark', 'Brown', 'mark@gmail.com', 'Australia', 29);
Insert Into person(name, surname, email, citizenship, age) VALUES('Julia', 'Schmidt', 'julia@yahoo.com', 'Austria', 25);
Insert Into person(name, surname, email, citizenship, age) VALUES('Hassan', 'Ali', 'hassan@hotmail.com', 'Iran', 33);
Insert Into person(name, surname, email, citizenship, age) VALUES('Zoe', 'Dubois', 'zoe@gmail.com', 'Belgium', 24);
Insert Into person(name, surname, email, citizenship, age) VALUES('Chen', 'Li', 'chen@yahoo.com', 'Taiwan', 28);
Insert Into person(name, surname, email, citizenship, age) VALUES('Pedro', 'Silva', 'pedro@hotmail.com', 'Portugal', 26);
Insert Into person(name, surname, email, citizenship, age) VALUES('Hannah', 'Williams', 'hannah@gmail.com', 'New Zealand', 30);
Insert Into person(name, surname, email, citizenship, age) VALUES('Abdul', 'Mohammed', 'abdul@yahoo.com', 'Turkey', 32);
Insert Into person(name, surname, email, citizenship, age) VALUES('Giulia', 'Bianchi', 'giulia@hotmail.com', 'Switzerland', 22);
Insert Into person(name, surname, email, citizenship, age) VALUES('Ryan', 'Miller', 'ryan@gmail.com', 'Ireland', 34);
Insert Into person(name, surname, email, citizenship, age) VALUES('Elena', 'Kovac', 'elena@yahoo.com', 'Slovenia', 21);
Insert Into person(name, surname, email, citizenship, age) VALUES('Hamza', 'Malik', 'hamza@hotmail.com', 'Morocco', 35);
Insert Into person(name, surname, email, citizenship, age) VALUES('Anna', 'Jensen', 'annaJe@gmail.com', 'Sweden', 23);
Insert Into person(name, surname, email, citizenship, age) VALUES('Lee', 'Kim', 'lee@yahoo.com', 'South Korea', 31);
Insert Into person(name, surname, email, citizenship, age) VALUES('Sofia', 'Lopez', 'sofia@hotmail.com', 'Argentina', 27);
Insert Into person(name, surname, email, citizenship, age) VALUES('Jack', 'Taylor', 'jack@gmail.com', 'USA', 29);
Insert Into person(name, surname, email, citizenship, age) VALUES('Lena', 'Meyer', 'lena@yahoo.com', 'Germany', 25);
Insert Into person(name, surname, email, citizenship, age) VALUES('Ali', 'Hassan', 'aliHa@hotmail.com', 'Iraq', 33);
Insert Into person(name, surname, email, citizenship, age) VALUES('Chloe', 'Martin', 'chloe@gmail.com', 'France', 24);
Insert Into person(name, surname, email, citizenship, age) VALUES('Wang', 'Zhang', 'wang@yahoo.com', 'China', 28);
Insert Into person(name, surname, email, citizenship, age) VALUES('Juan', 'Perez', 'juan@hotmail.com', 'Colombia', 26);
Insert Into person(name, surname, email, citizenship, age) VALUES('Emily', 'Jones', 'emily@gmail.com', 'UK', 30);
